name: genesis

services:
  auth:
    image: quay.io/keycloak/keycloak:26.6.1
    ports:
      - 8081:8080
      - 9000:9000
    volumes:
      - auth_data:/opt/keycloak/data
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: auth-admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: auth-admin
      KC_DB: postgres
      KC_DB_URL_HOST: auth_db
      KC_DB_URL_DATABASE: auth
      KC_DB_USERNAME: auth-db-admin
      KC_DB_PASSWORD: auth-db-admin
    depends_on:
      auth_db:
        condition: service_healthy
      auth_mail:
        condition: service_healthy
    command: start-dev

  auth_db:
    image: postgres:18.3
    ports:
      - 5432:5432
    volumes:
      - auth_db_data:/var/lib/postgresql/docker
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: auth-db-admin
      POSTGRES_PASSWORD: auth-db-admin
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "auth", "-U", "auth-db-admin"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

  auth_mail:
    image: axllent/mailpit:v1.29.7
    restart: unless-stopped
    volumes:
      - auth_mail_data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

networks:
  genesis:

volumes:
  auth_data:
  auth_db_data:
  auth_mail_data:
